#!/bin/sh

#
# Define init LSB shell functions
#

#
# Source vacteria's rc functions
#
. /lib/init/vct-functions

#
# Be sure that  start_daemon, killproc, and
# pidofproc will be script functions.
#
start_daemon()
{
    /sbin/start_daemon ${1+"$@"}

	return $?
}

killproc()
{
    /sbin/killproc ${1+"$@"}

	return $?
}

pidofproc()
{
    /sbin/pidofproc ${1+"$@"}

	return $?
}

statusproc()
{
	local P

	for P in ${@}
	do
		checkproc ${P}
		case ${?} in
			0 ) printf '%s is running with PIDs :\n%s\n' "${P}" "$(pidofproc ${P})" ;;
			1 ) printf '%s is not running but PID file found\n' "${P}" ;;
			3 ) printf '%s is not running\n' "${P}" ;;
		esac
	done

	return 0
}

#
# Logging of succes messages
#
log_success_msg()
{
    printf "$@"
    rc_done
}

#
# Logging of failure messages
#
log_failure_msg()
{
    printf "$@"
    rc_fail
}

#
# Logging of warn messages
#
log_warning_msg()
{
    printf "$@"
    rc_warn
}

#
# Loggin generic take action
#
log_action_msg()
{
	printf "${RC_BOLD}${@}${RC_NORMAL}\n"
}
