#!/bin/sh

###
# Vacteria System init script, Created on lun ene 10 14:12:34 CST 2011
# This file is free software and is released under GPL v2.1 or grant.
###

### BEGIN INIT INFO
# Provides:          halt
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     0
# Default-Stop:      
# X-Interactive:     
# X-vct-Provided-By: Vacteria
# Short-Description: Halts the system.
# Description:       Halts the system.
### END INIT INFO

. /lib/init/init-functions

rc_start()
{
	rc_message "Halting system"
	halt -d -f -i -p
}

case ${1} in
	start   ) rc_start   ;;
	*       ) rc_error   ;;
esac
