#!/bin/sh

###
# Vacteria System init script, Created on lun ene 10 14:12:34 CST 2011
# This file is free software and is released under GPL v2.1 or grant.
###

### BEGIN INIT INFO
# Provides:          hwclock
# Required-Start:    udev mountfs
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     S
# Default-Stop:      
# X-Interactive:     
# X-vct-Provided-By: Vacteria
# Short-Description: Stores and restores time from the hardware clock
# Description:       On boot, system time is obtained from hwclock.  The
#                    hardware clock can also be set on shutdown.
### END INIT INFO

. /lib/init/init-functions
. /etc/rc.conf.d/hwclock

set_params()
{
	if rc_bolean ${UTC}
	then
		params="${CLOCKPARAMS} --localtime"
	else
		params="${CLOCKPARAMS} --utc"
	fi
}
	
rc_start()
{
	set_params
		
	rc_message "Setting hardware clock"
	hwclock --systohc ${params} >/dev/null
	rc_return
}

rc_stop()
{
	set_params
		
	rc_message "Saving hardware clock"
	hwclock --hctosys ${params} >/dev/null
	rc-return
}

rc_restart()
{
	${0} stop
	sleep 1
	${0} start
}

case ${1} in
	start   ) rc_start   ;;
	stop    ) rc_stop    ;;
	restart ) rc_restart ;;
	reload  ) rc_reload  ;;
	status  ) rc_status  ;;
	*       ) rc_error   ;;
esac
