#!/bin/sh

###
# Vacteria Operating System init script, Created on "DATE"
# This file is free software and is released under GPL v2.1 or grant.
###

### BEGIN INIT INFO
# Provides:          service_name
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     
# Default-Stop:      
# X-Interactive:     
# X-vct-Provided-By: Vacteria
# Short-Description: single_line_description
# Description:       multiline_description
### END INIT INFO

. /lib/init/-init-functions || exit 6

rc_start()
{
	rc_message "My start message"
	start_daemon /path/to/command --arguments
	rc_return
}

rc_stop()
{
	rc_message "My stopt message"
	killproc /path/to/command
	rc_return
}

rc_restart()
{
	rc_stop
	sleep 1
	rc_start
}

rc_reload()
{
	rc_message "My reloading message"
	killproc -HUP /path/to/command
	rc_return
}

rc_status()
{
	statusproc /path/to/command
}

case ${1} in
	start   ) rc_start   ;;
	stop    ) rc_stop    ;;
	restart ) rc_restart ;;
	reload  ) rc_reload  ;;
	status  ) rc_status  ;;
	*       ) rc_error   ;;
esac
